### ISSUE TITLE
✅ 프로젝트 세팅

### ISSUE THREAD

**Issue by moondev03** [DEPthes/3rd-MVP-Neverland-Android#1]
## 💼 작업 설명

패키지 구조 세팅 및 Base, Util 코드 작성

<br>

## ✅ To-do

- [x] 패키지 구조 세팅
- [x] BaseActivity, BaseFragment 작성
- [x] Logger 라이브러리 추가
- [x] ViewModel, LiveData 추가
- [x] UiState 추가
- [x] 샘플 코드 작성
<br>

## ☁️ Reference

<br>
