### ISSUE TITLE
✅ 공통 공지사항 페이지 | 공지 유형 추가

### ISSUE THREAD

**Issue by moondev03** [DEPthes/3rd-MVP-Neverland-Android#20]
## 💼 작업 설명

<br>

## ✅ To-do

- [x] 현장실습지원 참여기업 안내 | Item 추가
- [x] 생활관 | 분류(자연/인문/공통) 필터
- [x] 생활관, 현장실습 참여 기업, 도서관, 교직 공지 조회 작업
<br>

## ☁️ Reference

<br>
