### ISSUE TITLE
✅ 디자인 시스템

### ISSUE THREAD

**Issue by moondev03** [DEPthes/3rd-MVP-Neverland-Android#3]
## 💼 작업 설명

디자인 시스템 정의
<br>

## ✅ To-do

- [x] Font: Pretandard
- [x] Font Style 정의 - Figma Typography 참고
- [x] Sample View 작성
- [x] Color 정의 - Figma Color Platte 참고
- [x] Icon Assets 추가 - Figma 참고

<br>

## ☁️ Reference

<br>
